<?php

namespace App\AI6\Shared\Security;

enum SecurityMeasure: string
{
    case LOGIN_EMAIL_CONFIRMATION = 'AI6_SECURITY_LOGIN_EMAIL_CONFIRMATION';
    case REQUIRE_PRIVILEGED_PASSKEY = 'AI6_SECURITY_REQUIRE_PRIVILEGED_PASSKEY';
    case REQUIRE_CRITICAL_ACTION_STEP_UP = 'AI6_SECURITY_REQUIRE_CRITICAL_ACTION_STEP_UP';
    case REQUIRE_HTTPS_OR_PRIVATE_ACCESS = 'AI6_SECURITY_REQUIRE_HTTPS_OR_PRIVATE_ACCESS';
    case REQUIRE_AGENT_SANDBOX = 'AI6_SECURITY_REQUIRE_AGENT_SANDBOX';
    case REQUIRE_CHECKER_NETWORK_ISOLATION = 'AI6_SECURITY_REQUIRE_CHECKER_NETWORK_ISOLATION';
    case REQUIRE_LLM_PRECOMMIT_REVIEW = 'AI6_SECURITY_REQUIRE_LLM_PRECOMMIT_REVIEW';

    public function controlGroup(): SecurityControlGroup
    {
        return match ($this) {
            self::LOGIN_EMAIL_CONFIRMATION => SecurityControlGroup::LOGIN_EMAIL_CONFIRMATION,
            self::REQUIRE_PRIVILEGED_PASSKEY,
            self::REQUIRE_CRITICAL_ACTION_STEP_UP => SecurityControlGroup::PRIVILEGED_AUTHENTICATION,
            self::REQUIRE_HTTPS_OR_PRIVATE_ACCESS => SecurityControlGroup::HTTPS_OR_PRIVATE_ACCESS,
            self::REQUIRE_AGENT_SANDBOX,
            self::REQUIRE_CHECKER_NETWORK_ISOLATION => SecurityControlGroup::EXECUTION_ISOLATION,
            self::REQUIRE_LLM_PRECOMMIT_REVIEW => SecurityControlGroup::LLM_PRECOMMIT_REVIEW,
        };
    }
}
