<?php

return [
    'runtime_role' => env('AI6_RUNTIME_ROLE', ''),
    'auth' => [
        'login_max_attempts' => env('AI6_AUTH_LOGIN_MAX_ATTEMPTS', '5'),
        'login_decay_seconds' => env('AI6_AUTH_LOGIN_DECAY_SECONDS', '60'),
        'session_lifetime_minutes' => env('AI6_AUTH_SESSION_LIFETIME_MINUTES', '120'),
        'login_confirmation_ttl_seconds' => env('AI6_AUTH_LOGIN_CONFIRMATION_TTL_SECONDS', '600'),
        'login_confirmation_max_attempts' => env('AI6_AUTH_LOGIN_CONFIRMATION_MAX_ATTEMPTS', '5'),
        'strong_authentication_max_attempts' => env('AI6_AUTH_STRONG_AUTHENTICATION_MAX_ATTEMPTS', '5'),
        'strong_authentication_decay_seconds' => env('AI6_AUTH_STRONG_AUTHENTICATION_DECAY_SECONDS', '300'),
        'login_confirmation_resend_cooldown_seconds' => env('AI6_AUTH_LOGIN_CONFIRMATION_RESEND_COOLDOWN_SECONDS', '30'),
        'step_up_window_seconds' => env('AI6_AUTH_STEP_UP_WINDOW_SECONDS', '300'),
        'enrollment_ttl_seconds' => env('AI6_AUTH_ENROLLMENT_TTL_SECONDS', '900'),
        'login_confirmation_email' => env('AI6_LOGIN_CONFIRMATION_EMAIL'),
    ],
    'http_hardening' => [
        'trusted_hosts' => env('AI6_HTTP_TRUSTED_HOSTS', 'localhost,127.0.0.1,::1'),
        'trusted_proxies' => env('AI6_HTTP_TRUSTED_PROXIES', ''),
        'session_same_site' => env('AI6_HTTP_SESSION_SAME_SITE', 'lax'),
        'script_asset_path' => '/assets/',
        'csp_directives' => [
            'default-src' => "'self'",
            'script-src' => '{asset-origin}',
            'style-src' => "'self'",
            'img-src' => "'self'",
            'font-src' => "'self'",
            'connect-src' => "'self'",
            'form-action' => "'self'",
            'base-uri' => "'none'",
            'object-src' => "'none'",
            'frame-ancestors' => "'none'",
        ],
    ],
    'security' => [
        'profile' => env('AI6_SECURITY_PROFILE', 'strict'),
        'acknowledge_reduced_mode' => env('AI6_SECURITY_ACKNOWLEDGE_REDUCED_MODE', 'false'),
        'measures' => [
            'AI6_SECURITY_LOGIN_EMAIL_CONFIRMATION' => env('AI6_SECURITY_LOGIN_EMAIL_CONFIRMATION', 'true'),
            'AI6_SECURITY_REQUIRE_PRIVILEGED_PASSKEY' => env('AI6_SECURITY_REQUIRE_PRIVILEGED_PASSKEY', 'true'),
            'AI6_SECURITY_REQUIRE_CRITICAL_ACTION_STEP_UP' => env('AI6_SECURITY_REQUIRE_CRITICAL_ACTION_STEP_UP', 'true'),
            'AI6_SECURITY_REQUIRE_HTTPS_OR_PRIVATE_ACCESS' => env('AI6_SECURITY_REQUIRE_HTTPS_OR_PRIVATE_ACCESS', 'true'),
            'AI6_SECURITY_REQUIRE_AGENT_SANDBOX' => env('AI6_SECURITY_REQUIRE_AGENT_SANDBOX', 'true'),
            'AI6_SECURITY_REQUIRE_CHECKER_NETWORK_ISOLATION' => env('AI6_SECURITY_REQUIRE_CHECKER_NETWORK_ISOLATION', 'true'),
            'AI6_SECURITY_REQUIRE_LLM_PRECOMMIT_REVIEW' => env('AI6_SECURITY_REQUIRE_LLM_PRECOMMIT_REVIEW', 'true'),
        ],
    ],
    'redaction' => [
        'environment' => env('APP_ENV', 'production'),
        'active_key_id' => env('AI6_REDACTION_ACTIVE_KEY_ID', 'app-key-v1'),
        'keys' => env('AI6_REDACTION_KEYS', ''),
        'app_key' => env('APP_KEY', ''),
    ],
    'process' => [
        'timeout_seconds' => env('AI6_PROCESS_TIMEOUT_SECONDS', '300'),
        'output_limit_bytes' => env('AI6_PROCESS_OUTPUT_LIMIT_BYTES', '1048576'),
        'cancel_grace_milliseconds' => env('AI6_PROCESS_CANCEL_GRACE_MILLISECONDS', '2000'),
        'wrapper_ready_timeout_seconds' => env('AI6_PROCESS_WRAPPER_READY_TIMEOUT_SECONDS', '30'),
        'wrapper_script' => base_path('app/AI6/Shared/Process/control-process-wrapper.sh'),
        'shell_binary' => env('AI6_PROCESS_SHELL_BINARY', '/usr/bin/dash'),
        'setsid_binary' => env('AI6_PROCESS_SETSID_BINARY', '/usr/bin/setsid'),
        'process_group_kill_binary' => env('AI6_PROCESS_GROUP_KILL_BINARY', '/usr/bin/kill'),
        'lock_directory' => env('AI6_EFFECT_LOCK_DIRECTORY', '/var/lib/ai6/managed/effect-locks'),
        'lock_object_count' => env('AI6_EFFECT_LOCK_OBJECT_COUNT', '64'),
        'lock_wait_milliseconds' => env('AI6_EFFECT_LOCK_WAIT_MILLISECONDS', '25000'),
        'lock_owner_uid' => env('AI6_EFFECT_LOCK_OWNER_UID', '0'),
    ],
    'git' => [
        'binary' => env('AI6_GIT_BINARY', '/usr/bin/git'),
        'ssh_binary' => env('AI6_GIT_SSH_BINARY', '/usr/bin/ssh'),
        'executable_path' => env('AI6_GIT_EXECUTABLE_PATH', '/usr/local/bin:/usr/bin:/bin'),
        'ssh_wrapper' => base_path('bin/ai6-git-ssh.sh'),
        'execution_home' => env('AI6_GIT_EXECUTION_HOME', storage_path('framework/ai6/git-home')),
        'xdg_config_home' => env('AI6_GIT_XDG_CONFIG_HOME', storage_path('framework/ai6/git-home/xdg')),
        'global_config' => env('AI6_GIT_GLOBAL_CONFIG', storage_path('framework/ai6/git-home/gitconfig')),
        'hooks_path' => env('AI6_GIT_HOOKS_PATH', storage_path('framework/ai6/git-hooks')),
        'allowed_hosts' => env('AI6_GIT_ALLOWED_HOSTS', ''),
        'allowed_remote_paths' => env('AI6_GIT_ALLOWED_REMOTE_PATHS', ''),
        'allowed_ref_patterns' => env('AI6_GIT_ALLOWED_REF_PATTERNS', 'refs/heads/*'),
        'pinned_host_keys' => env('AI6_GIT_PINNED_HOST_KEYS', ''),
    ],
    'control_operations' => [
        'managed_root' => env('AI6_MANAGED_PROJECT_ROOT', '/var/lib/ai6/managed'),
        'key_root' => env('AI6_DEPLOY_KEY_ROOT', '/var/lib/ai6/managed/deploy-keys'),
        'ssh_keygen_binary' => env('AI6_SSH_KEYGEN_BINARY', '/usr/bin/ssh-keygen'),
        'ssh_keygen_wrapper' => base_path('app/AI6/Git/generate-deploy-key.sh'),
        'known_hosts_file' => env('AI6_CONTROL_OPERATION_KNOWN_HOSTS_FILE', '/var/lib/ai6/managed/known_hosts'),
        'managed_ref_allowlist' => env('AI6_CONTROL_OPERATION_MANAGED_REF_ALLOWLIST', 'refs/heads/main'),
        'lease_seconds' => env('AI6_CONTROL_OPERATION_LEASE_SECONDS', '120'),
        'heartbeat_seconds' => env('AI6_CONTROL_OPERATION_HEARTBEAT_SECONDS', '30'),
        'reconciler_seconds' => env('AI6_CONTROL_OPERATION_RECONCILER_SECONDS', '30'),
        'max_attempts' => env('AI6_CONTROL_OPERATION_MAX_ATTEMPTS', '3'),
        'stale_seconds' => env('AI6_CONTROL_OPERATION_STALE_SECONDS', '300'),
        'reconciliation_budget' => env('AI6_CONTROL_OPERATION_RECONCILIATION_BUDGET', '8'),
        'refresh_base_path' => env('AI6_CONTROL_OPERATION_REFRESH_BASE_PATH', 'tickets'),
    ],
    'tickets' => [
        'validation_profile' => env('AI6_TICKET_VALIDATION_PROFILE', 'generic_v1'),
        'max_candidates' => env('AI6_TICKET_MAX_CANDIDATES', '100'),
    ],
    'ticket_mutations' => [
        'git_author_name' => env('AI6_TICKET_MUTATION_GIT_AUTHOR_NAME', 'AI6 Control Worker'),
        'git_author_email' => env('AI6_TICKET_MUTATION_GIT_AUTHOR_EMAIL', 'ai6-control@example.invalid'),
    ],
];
