<?php

declare(strict_types=1);

/*
 * Deterministic Codex CLI double for the AI6-033 contract tests.
 *
 * It mimics the exec surface of codex-cli 0.129.0-alpha.15 that CodexCliAdapter
 * uses: `--version`, `features list`, `exec [OPTIONS] -- -` with the prompt on
 * standard input, the JSONL event hull and the schema-bound final answer. It
 * observes the argument list, the environment, the working directory, the home
 * layout and a fixed set of discovery, credential and write probes, and writes
 * them next to its TMPDIR. It proves the AI6 wiring and the OS boundaries of
 * the calling role — never the internal sandbox of the real CLI (MG-01).
 *
 * The wrapper generated by FakeCodexBinary bakes the scenario and the version
 * line in as leading options, separated from the CLI arguments by `--`.
 */

$scenario = 'success';
$versionLine = 'codex-cli 0.129.0-alpha.15';
$argumentVector = $_SERVER['argv'] ?? [];
$arguments = is_array($argumentVector) ? array_values(array_slice($argumentVector, 1)) : [];
while ($arguments !== [] && $arguments[0] !== '--') {
    $option = (string) array_shift($arguments);
    if (str_starts_with($option, '--scenario=')) {
        $scenario = substr($option, strlen('--scenario='));
    } elseif (str_starts_with($option, '--version-string=')) {
        $versionLine = substr($option, strlen('--version-string='));
    }
}
array_shift($arguments);

if ($arguments === ['--version']) {
    if ($scenario === 'version_probe_fails') {
        fwrite(STDERR, "fake codex: version probe refused\n");
        exit(3);
    }
    echo $versionLine, "\n";
    exit(0);
}

$usageError = static function (string $message): never {
    fwrite(STDERR, 'error: '.$message."\n");
    exit(2);
};

// The feature surface of the pinned version: everything the binary knows,
// with the stage and the effective state the overrides of this call produce.
if (($arguments[0] ?? null) === 'features') {
    if (($arguments[1] ?? null) !== 'list') {
        $usageError('unrecognized features subcommand');
    }
    if ($scenario === 'feature_probe_fails') {
        fwrite(STDERR, "fake codex: feature probe refused\n");
        exit(3);
    }
    if ($scenario === 'feature_probe_invalid') {
        echo "plugins is off\n";
        exit(0);
    }
    $features = [
        'apply_patch_freeform' => ['under development', false],
        'apps' => ['stable', true],
        'browser_use' => ['stable', true],
        'browser_use_external' => ['stable', true],
        'collaboration_modes' => ['removed', true],
        'computer_use' => ['stable', true],
        'enable_request_compression' => ['stable', true],
        'fast_mode' => ['stable', true],
        'guardian_approval' => ['stable', true],
        'hooks' => ['stable', true],
        'image_generation' => ['stable', true],
        'in_app_browser' => ['stable', true],
        'memories' => ['experimental', false],
        'multi_agent' => ['stable', true],
        'personality' => ['stable', true],
        'plugins' => ['stable', true],
        'shell_snapshot' => ['stable', true],
        'shell_tool' => ['stable', true],
        'skill_mcp_dependency_install' => ['stable', true],
        'sqlite' => ['removed', true],
        'steer' => ['removed', true],
        'terminal_resize_reflow' => ['experimental', true],
        'tool_call_mcp_elicitation' => ['stable', true],
        'tool_search' => ['stable', true],
        'tool_suggest' => ['stable', true],
        'tui_app_server' => ['removed', true],
        'unavailable_dummy_tools' => ['stable', true],
        'unified_exec' => ['stable', false],
        'workspace_dependencies' => ['stable', true],
    ];
    if ($scenario === 'extension_enabled') {
        // A later version ships an extension surface the approved profile never named.
        $features['skill_marketplace'] = ['stable', true];
    }
    $index = 2;
    while ($index < count($arguments)) {
        if ($arguments[$index] === '--disable' && is_string($arguments[$index + 1] ?? null)) {
            $name = $arguments[$index + 1];
            if (! array_key_exists($name, $features)) {
                fwrite(STDERR, 'Error: Unknown feature flag: '.$name."\n");
                exit(1);
            }
            if ($scenario !== 'feature_switch_ignored') {
                $features[$name][1] = false;
            }
            $index += 2;

            continue;
        }
        $usageError('unexpected argument '.$arguments[$index]);
    }
    if ($scenario === 'feature_switch_missing') {
        // The pin no longer offers the switch at all, so its name never appears.
        unset($features['plugins']);
    }
    ksort($features, SORT_STRING);
    foreach ($features as $name => [$stage, $enabled]) {
        printf("%-40s%-19s%s\n", $name, $stage, $enabled ? 'true' : 'false');
    }
    exit(0);
}

if (($arguments[0] ?? null) !== 'exec') {
    $usageError('unrecognized subcommand');
}
$options = ['flags' => [], 'values' => [], 'config' => [], 'disable' => [], 'prompt' => null];
$booleanFlags = ['--json', '--ephemeral', '--ignore-user-config', '--ignore-rules', '--skip-git-repo-check'];
$valueFlags = ['--color', '--sandbox', '--cd', '--model', '--output-schema'];
$index = 1;
while ($index < count($arguments)) {
    $argument = $arguments[$index];
    if ($argument === '--') {
        $rest = array_slice($arguments, $index + 1);
        if (count($rest) !== 1) {
            $usageError('exactly one prompt argument is expected after --');
        }
        // Like the pinned version: `-` reads the instructions from standard input.
        $options['prompt'] = $rest[0] === '-' ? (string) stream_get_contents(STDIN) : $rest[0];
        break;
    }
    if (in_array($argument, $booleanFlags, true)) {
        $options['flags'][] = $argument;
        $index++;

        continue;
    }
    $value = $arguments[$index + 1] ?? null;
    if ($value === null) {
        $usageError('missing value for '.$argument);
    }
    if (in_array($argument, $valueFlags, true)) {
        $options['values'][$argument] = $value;
    } elseif ($argument === '--config') {
        $options['config'][] = $value;
    } elseif ($argument === '--disable') {
        $options['disable'][] = $value;
    } else {
        $usageError('unexpected argument '.$argument);
    }
    $index += 2;
}
if (! is_string($options['prompt'])) {
    $usageError('a prompt is required');
}

$temporary = getenv('TMPDIR');
if (! is_string($temporary) || ! is_dir($temporary)) {
    fwrite(STDERR, "fake codex: TMPDIR is not a directory\n");
    exit(4);
}
$observationPath = dirname($temporary).'/observation.json';
$home = (string) getenv('HOME');
$codexHome = (string) getenv('CODEX_HOME');
$cwd = str_replace('\\', '/', (string) getcwd());

$entries = static function (string $directory): array {
    if (! is_dir($directory)) {
        return ['<missing>'];
    }
    $found = array_values(array_diff(scandir($directory) ?: [], ['.', '..']));
    sort($found, SORT_STRING);

    return $found;
};
$writeProbe = static function (string $path): string {
    $handle = @fopen($path, 'ab');
    if (! is_resource($handle)) {
        return 'denied';
    }
    fclose($handle);
    if (@filesize($path) === 0) {
        @unlink($path);
    }

    return 'writable';
};
$digest = static function (string $path): string {
    $bytes = @file_get_contents($path);

    return $bytes === false ? 'missing' : 'sha256:'.hash('sha256', $bytes);
};

$observation = [
    'scenario' => $scenario,
    'argv' => $arguments,
    'options' => $options,
    'prompt_bytes' => strlen($options['prompt']),
    'prompt_sha256' => hash('sha256', $options['prompt']),
    'cwd' => $cwd,
    'env' => [],
    'home' => $home,
    'codex_home' => $codexHome,
    'home_entries' => $entries($home),
    'codex_home_entries' => $entries($codexHome),
    'auth' => is_file($codexHome.'/auth.json') && @file_get_contents($codexHome.'/auth.json') !== false ? 'readable' : 'missing',
    'auth_write' => $writeProbe($codexHome.'/auth.json'),
    'codex_home_write' => $writeProbe($codexHome.'/.ai6-fake-codex-probe'),
    'home_write' => $writeProbe($home.'/.ai6-fake-codex-probe'),
    'native_state' => [],
    'instruction_parent' => [],
    'workspace' => [],
    'schema' => null,
];
foreach (['APP_KEY', 'DB_DATABASE', 'MAIL_PASSWORD', 'AI6_GIT_SSH_KEY', 'AI6_GIT_KNOWN_HOSTS', 'SESSION_DRIVER',
    'AI6_RUNTIME_PROFILE', 'AI6_AUTH_FILE', 'OPENAI_API_KEY', 'XDG_CONFIG_HOME', 'HOME', 'CODEX_HOME', 'TMPDIR', 'PATH', 'LANG', 'LC_ALL'] as $name) {
    $observation['env'][$name] = getenv($name) === false ? 'missing' : 'present';
}
foreach (['sessions', 'history.jsonl', 'config.toml', 'AGENTS.md', 'skills', 'plugins', 'memories', 'log', 'models_cache.json'] as $native) {
    $observation['native_state']['codex_home:'.$native] = file_exists($codexHome.'/'.$native) ? 'present' : 'missing';
}
foreach (['.codex', '.config', '.cache', '.history', '.codex/config.toml', '.codex/sessions', '.codex/history.jsonl'] as $native) {
    $observation['native_state']['home:'.$native] = file_exists($home.'/'.$native) ? 'present' : 'missing';
}
$cursor = $cwd;
for ($level = 0; $level < 4; $level++) {
    $observation['instruction_parent'][(string) $level] = $digest(rtrim($cursor, '/').'/AGENTS.md');
    $cursor = dirname($cursor);
}
foreach ([
    '.git', '.git/refs', '.git/hooks', '.git/commondir', '../.git',
    '.codex', '.codex/config.toml', '.codex/plugins/plugin.json', '.codex/skills/SKILL.md', '.codex/commands/run.md',
    '.codex/rules/default.rules', '.claude/settings.json', '.mcp.json', 'mcp.json', '.gitconfig', '.git-credentials',
    '.agents', '.agents/skills/bait/SKILL.md', '.agents/hooks.json', '.agents/plugins/marketplace.json',
    'nested/AGENTS.md', 'AGENTS.md', 'app/Example.php',
] as $path) {
    $observation['workspace'][$path] = file_exists($cwd.'/'.$path) || is_link($cwd.'/'.$path) ? 'reachable' : 'missing';
}
$schemaPath = $options['values']['--output-schema'] ?? null;
$schema = is_string($schemaPath) ? json_decode((string) @file_get_contents($schemaPath), true) : null;
$observation['schema'] = is_array($schema) ? $schema : null;

// The documented discovery of the pinned version: the project root is the
// nearest ancestor holding `.git`, otherwise only the working directory is
// checked; from the root down, AGENTS.override.md wins over AGENTS.md.
$gitAncestor = null;
$cursor = $cwd;
for ($level = 0; $level < 64; $level++) {
    if (file_exists($cursor.'/.git')) {
        $gitAncestor = $cursor;
        break;
    }
    $parent = dirname($cursor);
    if ($parent === $cursor) {
        break;
    }
    $cursor = $parent;
}
$discoveryRoot = $gitAncestor ?? $cwd;
$discovered = [];
$directories = [$discoveryRoot];
if ($gitAncestor !== null && str_starts_with($cwd, rtrim($gitAncestor, '/').'/')) {
    $walk = $gitAncestor;
    foreach (explode('/', substr($cwd, strlen(rtrim($gitAncestor, '/')) + 1)) as $segment) {
        $walk .= '/'.$segment;
        $directories[] = $walk;
    }
}
foreach ($directories as $directory) {
    foreach (['AGENTS.override.md', 'AGENTS.md'] as $name) {
        if (is_file($directory.'/'.$name)) {
            $discovered[$directory.'/'.$name] = $digest($directory.'/'.$name);
            break;
        }
    }
}
$observation['discovery'] = ['git_ancestor' => $gitAncestor, 'root' => $discoveryRoot, 'files' => $discovered];

$sandbox = $options['values']['--sandbox'] ?? '';
$example = $cwd.'/app/Example.php';
if ($sandbox === 'read-only') {
    $probe = $cwd.'/review-write-probe';
    $created = @file_put_contents($probe, "review mutation\n", LOCK_EX);
    if ($created !== false) {
        // A platform without directory write protection let the probe through;
        // the observation records that, the file itself must not stay behind.
        @unlink($probe);
    }
    $observation['review_write'] = [
        'existing' => @file_put_contents($example, "review mutation\n", LOCK_EX) === false ? 'denied' : 'writable',
        'new' => $created === false ? 'denied' : 'writable',
    ];
}

$emit = static function (array $event): void {
    echo json_encode($event, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE), "\n";
};
$answer = static function (?array $schema, string $scenario): string {
    $properties = is_array($schema) ? ($schema['properties'] ?? []) : [];
    $constant = static fn (string $key): string => (string) ($properties[$key]['const'] ?? 'unbound');
    $statuses = $properties['status']['enum'] ?? ['completed'];
    $document = [
        'schema_version' => $constant('schema_version'),
        'status' => in_array('completed', $statuses, true) ? 'completed' : 'nothing_to_fix',
        'summary' => 'Deterministisches Fake-Codex-Ergebnis.',
        'prompt_snapshot_hash' => $constant('prompt_snapshot_hash'),
        'instruction_snapshot_hash' => $constant('instruction_snapshot_hash'),
        'provider_runtime_profile_hash' => $constant('provider_runtime_profile_hash'),
        'human_request' => null,
    ];
    if (array_key_exists('decisions', $properties)) {
        $document['decisions'] = [['key' => 'd1', 'title' => 'Umsetzung', 'rationale' => 'Deterministische Entscheidung.']];
        $document['changed_paths'] = $scenario === 'implementation_no_change' ? [] : ['app/Example.php'];
        $document['open_manual_gates'] = [];
        $document['implementation_summary'] = [
            'changed_components' => ['Example'], 'decisions' => ['Deterministische Entscheidung.'], 'assumptions' => [],
            'deviations' => [], 'known_limits' => [], 'tests' => [], 'review_focus' => ['app/Example.php'],
        ];
    }
    if (array_key_exists('findings', $properties)) {
        $document['findings'] = [];
        $document['criterion_coverage'] = array_map(
            static fn (string $criterion): array => ['criterion_id' => $criterion, 'status' => 'satisfied', 'evidence' => 'Deterministischer Nachweis.'],
            $properties['criterion_coverage']['items']['properties']['criterion_id']['enum'] ?? [],
        );
        $document['instruction_recommendations'] = [];
    }
    if (array_key_exists('finding_statuses', $properties)) {
        $document['finding_statuses'] = array_map(
            static fn (string $finding): array => ['finding_id' => $finding, 'status' => 'fixed', 'evidence' => 'Deterministische Re-Review-Evidenz.'],
            $properties['finding_statuses']['items']['properties']['finding_id']['enum'] ?? [],
        );
    }
    if (array_key_exists('instruction_patch', $properties)) {
        $document['instruction_patch'] = null;
    }

    return json_encode($document, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
};

file_put_contents($observationPath, json_encode($observation, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));

if ($scenario === 'materialize_extension') {
    // What the real CLI does at startup: unpack its bundled vendor skills into
    // $CODEX_HOME. The sealed projection must make that impossible; a test
    // opens the directory on purpose so the adapter's proof can fail once.
    @mkdir($codexHome.'/skills/.system/imagegen', 0700, true);
    @file_put_contents($codexHome.'/skills/.system/imagegen/SKILL.md', "bundled vendor skill\n");
}

if ($scenario === 'timeout') {
    // Keep proving liveness so a test can see the process-group termination
    // stop it: the pulse file goes stale once the runner has killed the group.
    for ($tick = 0; $tick < 600; $tick++) {
        file_put_contents($temporary.'/alive', (string) microtime(true));
        usleep(100000);
    }
    exit(0);
}
if ($scenario === 'output_flood') {
    $line = json_encode(['type' => 'item.completed', 'item' => ['id' => 'flood', 'type' => 'reasoning', 'text' => str_repeat('x', 4096)]])."\n";
    for ($count = 0; $count < 1024; $count++) {
        echo $line;
    }
    exit(0);
}

$emit(['type' => 'thread.started', 'thread_id' => '00000000-0000-4000-8000-000000000001']);
$emit(['type' => 'turn.started']);
if ($scenario === 'hull_invalid') {
    echo "this is not a json event\n";
}
if ($scenario !== 'missing_answer') {
    $emit(['type' => 'item.completed', 'item' => ['id' => 'item_0', 'type' => 'agent_message', 'text' => 'Ich prüfe den gebundenen Stand.']]);
}
if ($sandbox === 'workspace-write' && ! in_array($scenario, ['missing_answer', 'implementation_no_change'], true)) {
    $directory = dirname($example);
    if (! is_dir($directory)) {
        @mkdir($directory, 0770, true);
    }
    $contents = str_contains($options['prompt'], 'Behebe') || ($schema['properties']['finding_statuses'] ?? null) !== null
        ? "<?php\n\n// fake-codex-fix ".substr(hash('sha256', $options['prompt']), 0, 12)."\n"
        : "<?php\n\n// fake-codex-change\n";
    @file_put_contents($example, $contents);
    $emit(['type' => 'item.completed', 'item' => ['id' => 'item_1', 'type' => 'file_change', 'status' => 'completed', 'changes' => [['path' => 'app/Example.php', 'kind' => 'update']]]]);
}
$final = match ($scenario) {
    'invalid_answer' => '{"schema_version":',
    'foreign_schema' => '{"schema_version":"vendor.result.v9","status":"ok","summary":"Fremdes Schema."}',
    default => $answer($schema, $scenario),
};
if ($scenario === 'invalid_utf8') {
    // A hand-built line: json_encode() would refuse the invalid byte.
    echo '{"type":"item.completed","item":{"id":"item_2","type":"agent_message","text":"{\"schema_version\":\"', "\xff", '\"}"}}', "\n";
} elseif ($scenario !== 'missing_answer') {
    $emit(['type' => 'item.completed', 'item' => ['id' => 'item_2', 'type' => 'agent_message', 'text' => $final]]);
}
if ($scenario === 'double_answer') {
    // A second complete result answer inside the same turn: the contract
    // allows exactly one, and an intermediate message is not one of them.
    $emit(['type' => 'item.completed', 'item' => ['id' => 'item_2b', 'type' => 'agent_message', 'text' => $final]]);
}
if ($scenario === 'escaped_double_answer') {
    // The same second answer, but with the bound schema_version written as
    // JSON string escapes. The raw bytes name the version nowhere, the
    // decoded value is identical — a textual filter would miss it.
    $escaped = (string) preg_replace_callback(
        '/"schema_version":"([^"\\\\]+)"/',
        static function (array $match): string {
            $sequence = '';
            foreach (str_split($match[1]) as $character) {
                $sequence .= sprintf('\u%04x', ord($character));
            }

            return '"schema_version":"'.$sequence.'"';
        },
        $final,
    );
    if ($escaped === $final) {
        fwrite(STDERR, "fake codex: the escaped answer variant did not change the bytes\n");
        exit(5);
    }
    $emit(['type' => 'item.completed', 'item' => ['id' => 'item_2c', 'type' => 'agent_message', 'text' => $escaped]]);
}
if ($scenario === 'turn_failed') {
    $emit(['type' => 'turn.failed', 'error' => ['message' => 'fake provider failure']]);
    exit(0);
}
$usage = match ($scenario) {
    'usage_zero' => ['input_tokens' => 0, 'cached_input_tokens' => 0, 'output_tokens' => 0],
    'usage_missing' => null,
    default => ['input_tokens' => 120, 'cached_input_tokens' => 20, 'output_tokens' => 45],
};
$emit($usage === null ? ['type' => 'turn.completed'] : ['type' => 'turn.completed', 'usage' => $usage]);
if ($scenario === 'answer_after_turn') {
    // The contract forbids any message after the turn completed.
    $emit(['type' => 'item.completed', 'item' => ['id' => 'item_3', 'type' => 'agent_message', 'text' => 'Nachtrag nach Turnabschluss.']]);
}
if ($scenario === 'double_turn') {
    $emit(['type' => 'turn.started']);
    $emit(['type' => 'item.completed', 'item' => ['id' => 'item_3', 'type' => 'agent_message', 'text' => $final]]);
    $emit(['type' => 'turn.completed', 'usage' => ['input_tokens' => 1, 'cached_input_tokens' => 0, 'output_tokens' => 1]]);
}
if ($scenario === 'exit_failure') {
    fwrite(STDERR, "fake codex: exiting with failure\n");
    exit(1);
}
exit(0);
